repos:
    - repo: https://github.com/python/black
      rev: stable
      hooks:
          - id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: debug-statements
          - id: check-merge-conflict
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: check-added-large-files
          - id: check-json

    - repo: local
      hooks:
          - id: flake8
            name: flake8
            entry: flake8
            types: [python]
            language: python
            additional_dependencies:
                - flake8
                - flake8-comprehensions
                - flake8-bugbear
                - pep8-naming
                - flake8-eradicate
